image: "registry.gitlab.com/joewreschnig/emacs-cask-docker-image:alpine-edge"

before_script:
  - apk update && apk add bash

testing:
  script:
    - emacs --version
    - cask version
    - cask install
    - cask exec ert-runner --quiet
